 <!-- FOOTER -->
      
     </div><!-- /.container -->
    
    <footer class="footer">
      <div class="footer-container">
        <p class="text-muted pull-left">Dallas, Texas</p>
        <p class="text-muted pull-right">&copy; 2014 – 
	   <?php 
		echo date('Y');
		echo ' ';
		echo $_SERVER['HTTP_HOST'];
	   ?> 
	</p>
      </div><!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../Bootstrap_files/jquery.min.js"></script>
    <script src="../Bootstrap_files/bootstrap.min.js"></script>
    <script src="../Bootstrap_files/docs.min.js"></script>
  

</body></html>
