      <footer>
        <p>© Team2Awesome 2013</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../jumbo_files/jquery-1.10.2.min.js"></script>
    <script src="../jumbo_files/bootstrap.min.js"></script>
</body>
</html>